name: docker-build-and-push
on:
  push:
    branches:
      - "*"
      - feature/*
      - release/*
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  docker-build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Устанавливаем buildx + общий builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      # Кэшируем слои для повторных сборок
      - name: Configure Buildx cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create sanitized branch name
        id: sanitize
        run: echo "branch=$(echo ${GITHUB_REF_NAME} | sed 's/\//-/g')" >> $GITHUB_OUTPUT

      # Устанавливаем QEMU для эмуляции amd64/arm64
      - name: Enable QEMU emulation
        run: docker run --rm --privileged tonistiigi/binfmt --install all

      # --- BUILD AND PUSH ---

      - name: Build and push inage
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:amd64-${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Обновляем кэш после сборок
      - name: Move new cache
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # docker-build-arm64:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - uses: benjlevesque/short-sha@v3.0
  #       id: short-sha
  #       with:
  #         length: 8

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     # Устанавливаем buildx + общий builder
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #       with:
  #         install: true
  #         driver-opts: |
  #           image=moby/buildkit:latest
  #           network=host

  #     # Кэшируем слои для повторных сборок
  #     - name: Configure Buildx cache
  #       uses: actions/cache@v4
  #       with:
  #         path: /tmp/.buildx-cache
  #         key: ${{ runner.os }}-buildx-${{ github.ref_name }}
  #         restore-keys: |
  #           ${{ runner.os }}-buildx-

  #     - name: Create sanitized branch name
  #       id: sanitize
  #       run: echo "branch=$(echo ${GITHUB_REF_NAME} | sed 's/\//-/g')" >> $GITHUB_OUTPUT

  #     # Устанавливаем QEMU для эмуляции amd64/arm64
  #     - name: Enable QEMU emulation
  #       run: docker run --rm --privileged tonistiigi/binfmt --install all

  #     # --- BUILD AND PUSH ---

  #     - name: Build and push image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         provenance: false
  #         platforms: linux/arm64
  #         tags: |
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:arm64-${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }}
  #         cache-from: type=local,src=/tmp/.buildx-cache
  #         cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

  #     # Обновляем кэш после сборок
  #     - name: Move new cache
  #       if: always()
  #       run: |
  #         rm -rf /tmp/.buildx-cache
  #         mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # docker-multiarch-push:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - docker-build-arm64
  #     - docker-build-amd64
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - uses: benjlevesque/short-sha@v3.0
  #       id: short-sha
  #       with:
  #         length: 8

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Create sanitized branch name
  #       id: sanitize
  #       run: echo "branch=$(echo ${GITHUB_REF_NAME} | sed 's/\//-/g')" >> $GITHUB_OUTPUT

  #     - name: Create and push multi-arch image
  #       run: |
  #         docker manifest create \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }} \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:amd64-${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }} \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:arm64-${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }}

  #         docker manifest annotate \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }} \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:amd64-${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }} \
  #           --arch amd64

  #         docker manifest annotate \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }} \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:arm64-${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }} \
  #           --arch arm64

  #         docker manifest push \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/secret-copy-operator:${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }}
