name: Test Chart

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: ./.github/actions/setup-go-env

      - name: Setup Kind
        uses: ./.github/actions/setup-kind

      - name: Build and load image
        run: |
          make docker-build IMG=secret-copy-operator:v0.1.0
          kind load docker-image secret-copy-operator:v0.1.0

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Lint Helm Chart
        run: |
          helm lint ./dist/chart

# TODO: Uncomment if cert-manager is enabled
#      - name: Install cert-manager via Helm (wait for readiness)
#        run: |
#          helm repo add jetstack https://charts.jetstack.io
#          helm repo update
#          helm install cert-manager jetstack/cert-manager \
#            --namespace cert-manager \
#            --create-namespace \
#            --set crds.enabled=true \
#            --wait \
#            --timeout 300s

# TODO: Uncomment if Prometheus is enabled
#      - name: Install Prometheus Operator CRDs
#        run: |
#          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
#          helm repo update
#          helm install prometheus-crds prometheus-community/prometheus-operator-crds

      - name: Install Helm chart for project
        run: |
          helm install my-release ./dist/chart --create-namespace --namespace secret-copy-operator-system

      - name: Check Helm release status
        run: |
          helm status my-release --namespace secret-copy-operator-system
